### ISSUE TITLE
params如果没有password键时会报错

### ISSUE THREAD

**Issue by zacksleo** [monster-hunter/oauth2-redis#1]
`[yii\base\ErrorException] Undefined index: password  `

**Comment by monster-hunter** [comment]
需要修改一下init方法

**Comment by zacksleo** [comment]
` public $clientClass ` 这个应该是没有什么必要，如果能换其他客户端的库，但又不能保证有 `expire`, `del`, ` hgetall` 等等这些方式，这个库还是最终依赖 predis 库

**Comment by monster-hunter** [comment]
php自带的扩展还能用

**Comment by zacksleo** [comment]
redis-relational-database 这个名字起的不是很好，毕竟无法通用，这个和yii2-oauth2-server (oauth2) 密不可分，可以叫`oauth2-reids`之类的名字

**Comment by zacksleo** [comment]
> php自带的扩展还能用

那可以通过接口之类的实现吧，首先定义好接口， 然后具体的依赖具体实现

**Comment by monster-hunter** [comment]
恩 我改一下名字

**Comment by monster-hunter** [comment]
最初是考虑predis和redis可以随意切换，但是对于业务来说弄得复杂了

**Comment by zacksleo** [comment]
是的，接入的时候，使用不够简单。另外命名建议 ：

| 原名  | 新名  | 
|---|---|
| init()  |  __construct(array $params) |   
| hset($token, array $arr)  | setToken(string $token, array $array) |  
| hget($token)  | getToken(string $token)  |   
| deleteByToken($token) | deleteToken(string $token) |
| deleteByUserId($userId) | deleteUserToken(integer $userId)|
| deleteByClientId($clientId) | deleteClientToken(integer $clientId)
| deleteByUserIdAndClientId($clientId, $userId)| deleteUserClientToken(integer $userId, integer $clientId)|
|revokeOldToken($currentToken, $clientId, $userId) | deleteOldToken(string $currentToken, integer $userId, string $clientId)|

**Comment by monster-hunter** [comment]
是的 设计成接口 然后set一下 比这种方式好很多

**Comment by monster-hunter** [comment]
get it
